FROM ubi9-minimal:latest

LABEL MAINTAINER="Johan <jwennerb@redhat.com>"

ENV PORT 8080

RUN microdnf install -y httpd && \
    microdnf clean all

RUN sed -ri -e "/^Listen 80/c\Listen ${PORT}" /etc/httpd/conf/httpd.conf && \
    chown -R apache:apache /etc/httpd/logs/ && \
    chown -R apache:apache /run/httpd/

EXPOSE ${PORT}

COPY content/ /var/www/html

RUN chown -R apache:apache /var/www/html
RUN chmod -R +rx /var/www/html

USER apache

CMD ["httpd", "-D", "FOREGROUND"]
