FROM registry.stage.redhat.io/rhel10/rhel-bootc:10.1
#FROM registry.redhat.io/rhel10/rhel-bootc:10.0

LABEL MAINTAINER="IT Ops"

# Install packages
RUN dnf install -y \
  bash-completion \
  bind-utils \
  firewalld \
  glibc-langpack-en \
  glibc-minimal-langpack \
  man-pages \
  podman \
  python3 \
  rhc \
  setools-console \
  && rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

#vim-enhanced \

# QEMU/KVM, OpenShift Virtualization
#RUN dnf install -y cloud-init qemu-guest-agent && \
#    systemctl enable cloud-init qemu-guest-agent && \
#    rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

# Copy config, utils
COPY etc etc
COPY usr usr

# Red Hat Connect, Insights
RUN systemctl enable rhc-connect && \
    touch /etc/rhc/.run_rhc_connect_next_boot

RUN bootc container lint
