FROM quay.io/jwennerberg/soe-bootc:latest

RUN dnf install -y httpd && rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

RUN echo '<h1 style="text-align:center;">Welcome to image mode for RHEL</h1>' >> /var/www/html/index.html
