# Base on latest RHEL 10 SOE
#FROM satellite.summit.lab.a.wnn.se/rh_lab/rhel-bootc/rhel-soe-bootc:10
FROM quay.io/jwennerberg/soe-bootc:10

LABEL org.opencontainers.image.authors="Internal team tbd" \
      org.opencontainers.image.version="10.0-app1.2"

# Add extra system dependencies or services
RUN dnf install -y postgresql && \
    rm -rf /var/{cache,log} /var/lib/{dnf,rhsm}

# Copy environment data
COPY etc etc

# Add pgvector
COPY quadlets/pgvector/pgvector.container /usr/share/containers/systemd/

# Add ObjectDetection containerized app
COPY quadlets/object-detection/objectdetection.container /usr/share/containers/systemd/

# Enable systemd services
RUN ln -s ../objectdetection.target /usr/lib/systemd/system/default.target.wants && \
    ln -s ../pgvector.target /usr/lib/systemd/system/default.target.wants

# Enable systemd services and configure bootc logical bound images
#RUN ln -s ../objectdetection.target /usr/lib/systemd/system/default.target.wants && \
#    ln -s ../pgvector.target /usr/lib/systemd/system/default.target.wants && \
#    ln -s /usr/share/containers/systemd/pgvector.container /usr/lib/bootc/bound-images.d/pgvector.container && \
#    ln -s /usr/share/containers/systemd/objectdetection.container /usr/lib/bootc/bound-images.d/objectdetection.container

# RHEL Image Mode lint
RUN bootc container lint
